#!/bin/sh
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# ./show_unused
# Print unused patches
cd "$(dirname "$0")"
for i in *.patch; do grep "^$i" patches >/dev/null || echo $i; done
