# THIS FILE IS GENERATED. DO NOT EDIT MANUALLY.

ALL_BOARDS = [
    'amd64-generic', 'arm-generic', 'arm64-generic', 'asurada',
    'asurada-zephyr', 'atlas', 'beaglebone', 'beaglebone_servo', 'betty-arc-r',
    'betty-arc-s', 'betty-arcvm-master', 'bob', 'brya', 'brya-manatee', 'bubs',
    'caroline', 'caroline-kernelnext', 'cave', 'cherry', 'coral', 'cyan',
    'dedede', 'drallion', 'edgar', 'elm', 'endeavour', 'eve', 'eve-arc-r',
    'eve-kernelnext', 'fizz', 'fizz-labstation', 'gale', 'glados', 'grunt',
    'grunt-arc-r', 'grunt-kernelnext', 'guybrush', 'hana', 'hatch',
    'hatch-arc-r', 'hatch-arc-s', 'hatch-borealis', 'hatch-manatee',
    'herobrine', 'jacuzzi', 'kalista', 'kevin', 'kevin64', 'kip', 'kukui',
    'kukui-arc-r', 'majolica', 'mistral', 'mushu', 'nami', 'nocturne', 'novato',
    'novato-arc64', 'octopus', 'puff', 'rammus', 'rammus-arc-r', 'reef',
    'reven', 'sarien', 'scarlet', 'sentry', 'sludge', 'strongbad', 'tael',
    'tatl', 'trogdor', 'trogdor-kernelnext', 'trogdor-zephyr', 'trogdor64',
    'veyron_rialto', 'viking', 'volteer', 'volteer-borealis', 'volteer-manatee',
    'volteer-zephyr', 'winky', 'wizpig', 'zork-floss'
]
DEFAULT_BOARDS = [
    'volteer', 'endeavour', 'mistral', 'octopus', 'sludge', 'strongbad',
    'novato', 'kevin', 'atlas', 'eve', 'kukui', 'scarlet', 'tael',
    'veyron_rialto', 'zork-floss'
]

BOARDS_MAPPING = {
    'all': ALL_BOARDS,
    'default': DEFAULT_BOARDS,
}

# Not used. For reference only.
DEFAULT_BOARDS_REASON = {
    'volteer': {
        'chromeos-base/cbor', 'chromeos-base/autotest-tests',
        'net-print/cups_proxy', 'chromeos-base/factory_runtime_probe',
        'chromeos-base/cryptohome', 'chromeos-base/permission_broker-client',
        'chromeos-base/imageloader-client', 'chromeos-base/chromeos-init',
        'chromeos-base/crosdns', 'chromeos-base/arc-setup',
        'chromeos-base/u2fd', 'chromeos-base/missive',
        'chromeos-base/diagnostics', 'chromeos-base/cdm-oemcrypto',
        'chromeos-base/power_manager', 'chromeos-base/chromeos-config-tools',
        'chromeos-base/mount-passthrough', 'media-libs/dlm',
        'chromeos-base/session_manager-client', 'chromeos-base/smbprovider',
        'chromeos-base/chaps', 'chromeos-base/libhwsec-foundation',
        'chromeos-base/timberslide', 'chromeos-base/virtual-usb-printer',
        'chromeos-base/power_manager-client', 'dev-util/bsdiff',
        'dev-util/puffin', 'chromeos-base/vm_protos',
        'chromeos-base/biod_proxy', 'chromeos-base/cdm-oemcrypto-hw-test',
        'chromeos-base/arc-apk-cache', 'chromeos-base/libvda',
        'dev-libs/libutf', 'media-libs/cros-camera-hal-intel-ipu6',
        'chromeos-base/shill', 'chromeos-base/dns-proxy',
        'media-libs/cros-camera-v4l2_test', 'chromeos-base/mtpd',
        'chromeos-base/typecd', 'chromeos-base/chromeos-storage-info',
        'chromeos-base/tpm_softclear_utils', 'chromeos-base/update_engine',
        'dev-go/perfetto-protos',
        'media-libs/cros-camera-libcamera_connector_test',
        'chromeos-base/bootstat', 'chromeos-base/chromeos-login',
        'chromeos-base/iioservice', 'dev-libs/marisa-aosp',
        'chromeos-base/cros-camera-android-deps', 'dev-libs/libtextclassifier',
        'chromeos-base/cros-camera-libs', 'chromeos-base/secanomalyd',
        'chromeos-base/intel-nnhal', 'chromeos-base/perfetto_simple_producer',
        'chromeos-base/kerberos', 'net-print/cups',
        'chromeos-base/modem-utilities', 'chromeos-base/authpolicy',
        'chromeos-base/crash-reporter', 'chromeos-base/arcvm-forward-pstore',
        'chromeos-base/dev-install', 'net-wireless/bluez',
        'chromeos-base/libtpmcrypto', 'chromeos-base/secure-erase-file',
        'chromeos-base/vpn-manager', 'chromeos-base/mist',
        'chromeos-base/libcontainer', 'chromeos-base/trunks',
        'chromeos-base/chromeos-dbus-bindings', 'chromeos-base/policy-go-proto',
        'chromeos-base/vm_host_tools', 'chromeos-base/libpasswordprovider',
        'chromeos-base/easy-unlock', 'chromeos-base/quipper',
        'chromeos-base/biod', 'chromeos-base/cryptohome-dev-utils',
        'chromeos-base/system-proxy', 'chromeos-base/tpm_manager',
        'chromeos-base/autotest-tests-security', 'chromeos-base/metrics',
        'chromeos-base/libvda-gpu-tests', 'chromeos-base/dlcservice-client',
        'chromeos-base/ml-benchmark', 'chromeos-base/permission_broker',
        'chromeos-base/system_api', 'chromeos-base/attestation-client',
        'chromeos-base/cros-camera', 'chromeos-base/hardware_verifier_proto',
        'chromeos-base/debugd-client', 'chromeos-base/libbrillo',
        'chromeos-base/pciguard', 'chromeos-base/midis',
        'chromeos-base/attestation', 'chromeos-base/imageloader',
        'chromeos-base/aosp-frameworks-ml-nn',
        'chromeos-base/ml-benchmark-drivers', 'chromeos-base/shill-net',
        'chromeos-base/arcvm-mojo-proxy', 'chromeos-base/patchpanel',
        'chromeos-base/arc-host-clock-service',
        'chromeos-base/screen-capture-utils', 'chromeos-base/debugd',
        'chromeos-base/virtual-file-provider',
        'chromeos-base/update_engine-client',
        'chromeos-base/arcvm-boot-notification-server',
        'chromeos-base/aosp-frameworks-ml-nn-vts', 'chromeos-base/dlcservice',
        'chromeos-base/cros-disks', 'chromeos-base/chromeos-installer',
        'chromeos-base/arc-data-snapshotd', 'chromeos-base/g2f_tools',
        'chromeos-base/lorgnette', 'chromeos-base/verity',
        'chromeos-base/croslog', 'chromeos-base/drivefs', 'chromeos-base/smbfs',
        'media-libs/cros-camera-hal-usb', 'chromeos-base/libhwsec',
        'chromeos-base/cros-camera-tool', 'chromeos-base/ml',
        'chromeos-base/dlp', 'chromeos-base/libec',
        'chromeos-base/bootlockbox-client', 'chromeos-base/nnapi',
        'chromeos-base/secure-wipe', 'chromeos-base/chromeos-common-script',
        'net-print/brother_mlaser', 'chromeos-base/iioservice_simpleclient',
        'chromeos-base/mems_setup', 'chromeos-base/usb_bouncer',
        'chromeos-base/arc-adbd', 'chromeos-base/drivefs-ipc',
        'chromeos-base/shill-client', 'chromeos-base/arc-keymaster',
        'chromeos-base/tast-local-helpers-cros',
        'chromeos-base/shill-dbus-client', 'chromeos-base/lorgnette_cli',
        'chromeos-base/libipp', 'chromeos-base/oobe_config',
        'chromeos-base/easy-unlock-crypto', 'chromeos-base/ml-cmdline',
        'chromeos-base/patchpanel-client', 'chromeos-base/lexmark-fax-pnh',
        'chromeos-base/libchromeos-ui', 'media-libs/cros-camera-libjea_test',
        'chromeos-base/libmems', 'chromeos-base/run_oci',
        'chromeos-base/syslog-cat', 'chromeos-base/p2p',
        'media-libs/cros-camera-test', 'chromeos-base/chromeos-imageburner',
        'chromeos-base/libiioservice_ipc', 'chromeos-base/foomatic_shell',
        'chromeos-base/hwsec-test-utils', 'chromeos-base/tpm_manager-client',
        'chromeos-base/policy_utils', 'chromeos-base/cryptohome-client',
        'chromeos-base/chromeos-trim'
    },
    'endeavour': {
        'sys-apps/sis-updater', 'sys-apps/huddly-monitor', 'sys-apps/hotline',
        'media-libs/cros-camera-hal-ip', 'sys-apps/hotlog',
        'sys-apps/mimo-monitor', 'sys-apps/logitech-updater',
        'sys-apps/mimo-updater', 'chromeos-base/viking-hid',
        'sys-apps/huddly-falcon-updater', 'sys-apps/cecservice',
        'sys-apps/bizlink-updater', 'chromeos-base/mri_package',
        'chromeos-base/atrusctl', 'sys-apps/huddly-updater',
        'sys-apps/aver-updater', 'chromeos-base/ipaudio-alsa-plugin',
        'sys-apps/mimo-houston-mcu-updater', 'chromeos-base/ip-peripheral',
        'chromeos-base/cfm-dfu-notification'
    },
    'mistral': {
        'chromeos-base/ap-https-server', 'chromeos-base/ap-otp',
        'chromeos-base/buffet', 'chromeos-base/ap-net', 'chromeos-base/ap-aogh',
        'chromeos-base/ap-security', 'chromeos-base/sealed_storage',
        'chromeos-base/webserver', 'chromeos-base/ap-daemons',
        'chromeos-base/libweave', 'chromeos-base/ap-infra',
        'chromeos-base/actions', 'chromeos-base/ap-wireless',
        'chromeos-base/ap-scm', 'chromeos-base/thermald',
        'chromeos-base/nest-nn', 'chromeos-base/ap-common-go',
        'chromeos-base/gdisp', 'chromeos-base/feedback'
    },
    'octopus': {
        'chromeos-base/runtime_probe', 'chromeos-base/arc-sdcard',
        'chromeos-base/arc-appfuse', 'chromeos-base/arc-obb-mounter',
        'chromeos-base/fibocom-firmware', 'chromeos-base/hardware_verifier',
        'chromeos-base/disk_updater', 'chromeos-base/modemfwd'
    },
    'sludge': {
        'chromeos-base/mcastd', 'chromeos-base/sommelier',
        'chromeos-base/diagnostics-dpsl-test', 'chromeos-base/vm_guest_tools',
        'chromeos-base/ndproxyd'
    },
    'strongbad': {
        'chromeos-base/glib-bridge', 'chromeos-base/hammerd-test-utils',
        'chromeos-base/hermes', 'chromeos-base/hammerd',
        'chromeos-base/google-lpa'
    },
    'novato': {
        'chromeos-base/hpsd', 'chromeos-base/tpm2-simulator',
        'chromeos-base/goldfishd', 'chromeos-base/hps-tool'
    },
    'kevin': {'chromeos-base/touch_firmware_calibration', 'app-crypt/trousers'},
    'atlas': {'media-libs/cros-camera-hal-intel-ipu3'},
    'eve': {'chromeos-base/st_flash'},
    'kukui': {'media-libs/cros-camera-hal-mtk'},
    'scarlet': {'media-libs/cros-camera-hal-rockchip-isp1'},
    'tael': {'chromeos-base/termina_container_tools'},
    'veyron_rialto': {'chromeos-base/rialto-services'},
    'zork-floss': {'net-wireless/floss'}
}
