#ifndef BASE_CLANG_PROFILING_BUILDFLAGS_H_
#define BASE_CLANG_PROFILING_BUILDFLAGS_H_
#include "build/buildflag.h"
#define BUILDFLAG_INTERNAL_CLANG_PROFILING() (0)
#define BUILDFLAG_INTERNAL_ENABLE_GDBINIT_WARNING() (0)
#endif // BASE_CLANG_PROFILING_BUILDFLAGS_H_
