#ifndef BASE_TRACING_BUILDFLAGS_H_
#define BASE_TRACING_BUILDFLAGS_H_
#include "build/buildflag.h"
#define BUILDFLAG_INTERNAL_ENABLE_BASE_TRACING() (0)
#define BUILDFLAG_INTERNAL_USE_PERFETTO_CLIENT_LIBRARY() (0)
#endif // BASE_TRACING_BUILDFLAGS_H_
